#### ndarrayの生成

In [1]:
import numpy as np

In [2]:
a1 = np.array([5, 9, 1])
print(a1)

[5 9 1]


In [3]:
a2 = np.array([[1, 2, 3],[4, 5, 6]])
print(a2)

[[1 2 3]
 [4 5 6]]


In [4]:
print(a1.shape)

(3,)


In [5]:
print(a2.shape)

(2, 3)


#### ndarrayの算術演算

In [6]:
print(a1 + 10)


[15 19 11]


In [7]:
print(a1 - 1)


[4 8 0]


In [8]:
print(1 / a1)


[0.2        0.11111111 1.        ]


In [9]:
print(a1 * a1)


[25 81  1]


In [10]:
print(a1 ** 3)

[125 729   1]


#### ブロードキャスト

In [11]:
a1 = np.array([[0], [1], [2]])
b1 = np.array([1, 2, 3])
print(a1 + b1)

[[1 2 3]
 [2 3 4]
 [3 4 5]]


In [12]:
a2 = np.array([[0, 1], [2, 3], [4, 5]])
b2 = np.array([[1, 2, 3], [4, 5, 6]])
print(a2 + b2)

ValueError: operands could not be broadcast together with shapes (3,2) (2,3) 

In [13]:
a3 = np.array([[[1, 2, 3], [4, 5, 6]], [[7, 8, 9], [10, 11, 12]]])
b3 = np.array([[1], [4]])
print(a3 + b3)

[[[ 2  3  4]
  [ 8  9 10]]

 [[ 8  9 10]
  [14 15 16]]]
